// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8cyuHOJHTtA_RDDKcKrMunClMahESqOY',
    appId: '1:904496121497:web:359ae64e8c3eefd6045a08',
    messagingSenderId: '904496121497',
    projectId: 'tucky-6aebe',
    authDomain: 'tucky-6aebe.firebaseapp.com',
    storageBucket: 'tucky-6aebe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANJEtXSE1Ot8f0ybEhZnsOm3MAiWA5iZM',
    appId: '1:904496121497:android:c144c2037a682cad045a08',
    messagingSenderId: '904496121497',
    projectId: 'tucky-6aebe',
    storageBucket: 'tucky-6aebe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9XJ9nzHkdroLo-8StUHm6nFV1-8B8l8w',
    appId: '1:904496121497:ios:f291c8b032bbe919045a08',
    messagingSenderId: '904496121497',
    projectId: 'tucky-6aebe',
    storageBucket: 'tucky-6aebe.firebasestorage.app',
    iosBundleId: 'com.example.tucky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9XJ9nzHkdroLo-8StUHm6nFV1-8B8l8w',
    appId: '1:904496121497:ios:f291c8b032bbe919045a08',
    messagingSenderId: '904496121497',
    projectId: 'tucky-6aebe',
    storageBucket: 'tucky-6aebe.firebasestorage.app',
    iosBundleId: 'com.example.tucky',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8cyuHOJHTtA_RDDKcKrMunClMahESqOY',
    appId: '1:904496121497:web:5df82fdb02321fb5045a08',
    messagingSenderId: '904496121497',
    projectId: 'tucky-6aebe',
    authDomain: 'tucky-6aebe.firebaseapp.com',
    storageBucket: 'tucky-6aebe.firebasestorage.app',
  );
}
